/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CpZoneRouteImport } from './routes/cp-zone'
import { Route as DictionaryRouteImport } from './routes/dictionary'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ForumIndexRouteImport } from './routes/forum.index'
import { Route as ForumPostIdRouteImport } from './routes/forum.$postId'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as AuthenticatedForumNewRouteImport } from './routes/_authenticated/forum.new'
import { Route as AuthenticatedProfileUserIdRouteImport } from './routes/_authenticated/profile.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CpZoneRoute = CpZoneRouteImport.update({
  id: '/cp-zone',
  path: '/cp-zone',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionaryRoute = DictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumPostIdRoute = ForumPostIdRouteImport.update({
  id: '/forum/$postId',
  path: '/forum/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedForumNewRoute = AuthenticatedForumNewRouteImport.update({
  id: '/forum/new',
  path: '/forum/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileUserIdRoute =
  AuthenticatedProfileUserIdRouteImport.update({
    id: '/profile/$userId',
    path: '/profile/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cp-zone': typeof CpZoneRoute
  '/dictionary': typeof DictionaryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/practice': typeof PracticeRoute
  '/reference': typeof ReferenceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/forum/$postId': typeof ForumPostIdRoute
  '/forum/': typeof ForumIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/forum/new': typeof AuthenticatedForumNewRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cp-zone': typeof CpZoneRoute
  '/dictionary': typeof DictionaryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/practice': typeof PracticeRoute
  '/reference': typeof ReferenceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/forum/$postId': typeof ForumPostIdRoute
  '/forum': typeof ForumIndexRoute
  '/learn': typeof LearnIndexRoute
  '/forum/new': typeof AuthenticatedForumNewRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cp-zone': typeof CpZoneRoute
  '/dictionary': typeof DictionaryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/practice': typeof PracticeRoute
  '/reference': typeof ReferenceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/forum/$postId': typeof ForumPostIdRoute
  '/forum/': typeof ForumIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/_authenticated/forum/new': typeof AuthenticatedForumNewRoute
  '/_authenticated/profile/$userId': typeof AuthenticatedProfileUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cp-zone'
    | '/dictionary'
    | '/leaderboard'
    | '/practice'
    | '/reference'
    | '/reset-password'
    | '/admin'
    | '/forum/$postId'
    | '/forum/'
    | '/learn/'
    | '/forum/new'
    | '/profile/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cp-zone'
    | '/dictionary'
    | '/leaderboard'
    | '/practice'
    | '/reference'
    | '/reset-password'
    | '/admin'
    | '/forum/$postId'
    | '/forum'
    | '/learn'
    | '/forum/new'
    | '/profile/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cp-zone'
    | '/dictionary'
    | '/leaderboard'
    | '/practice'
    | '/reference'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/forum/$postId'
    | '/forum/'
    | '/learn/'
    | '/_authenticated/forum/new'
    | '/_authenticated/profile/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CpZoneRoute: typeof CpZoneRoute
  DictionaryRoute: typeof DictionaryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PracticeRoute: typeof PracticeRoute
  ReferenceRoute: typeof ReferenceRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ForumPostIdRoute: typeof ForumPostIdRoute
  ForumIndexRoute: typeof ForumIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cp-zone': {
      id: '/cp-zone'
      path: '/cp-zone'
      fullPath: '/cp-zone'
      preLoaderRoute: typeof CpZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary': {
      id: '/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof DictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/forum/': {
      id: '/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$postId': {
      id: '/forum/$postId'
      path: '/forum/$postId'
      fullPath: '/forum/$postId'
      preLoaderRoute: typeof ForumPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/forum/new': {
      id: '/_authenticated/forum/new'
      path: '/forum/new'
      fullPath: '/forum/new'
      preLoaderRoute: typeof AuthenticatedForumNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/$userId': {
      id: '/_authenticated/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AuthenticatedProfileUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedForumNewRoute: typeof AuthenticatedForumNewRoute
  AuthenticatedProfileUserIdRoute: typeof AuthenticatedProfileUserIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedForumNewRoute: AuthenticatedForumNewRoute,
  AuthenticatedProfileUserIdRoute: AuthenticatedProfileUserIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CpZoneRoute: CpZoneRoute,
  DictionaryRoute: DictionaryRoute,
  LeaderboardRoute: LeaderboardRoute,
  PracticeRoute: PracticeRoute,
  ReferenceRoute: ReferenceRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ForumPostIdRoute: ForumPostIdRoute,
  ForumIndexRoute: ForumIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
