/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CpZoneRouteImport } from './routes/cp-zone'
import { Route as DictionaryRouteImport } from './routes/dictionary'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ReferenceRouteImport } from './routes/reference'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMenteesRouteImport } from './routes/_authenticated/mentees'
import { Route as AuthenticatedReportingRouteImport } from './routes/_authenticated/reporting'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as CertificateCertificateCodeRouteImport } from './routes/certificate.$certificateCode'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as ForumIndexRouteImport } from './routes/forum.index'
import { Route as ForumPostIdRouteImport } from './routes/forum.$postId'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnCourseIdRouteImport } from './routes/learn.$courseId'
import { Route as PathsIndexRouteImport } from './routes/paths.index'
import { Route as PathsPathIdRouteImport } from './routes/paths.$pathId'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin_.analytics'
import { Route as AuthenticatedForumNewRouteImport } from './routes/_authenticated/forum.new'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated/groups.index'
import { Route as AuthenticatedGroupsGroupIdRouteImport } from './routes/_authenticated/groups.$groupId'
import { Route as AuthenticatedProfileUserIdRouteImport } from './routes/_authenticated/profile.$userId'
import { Route as PracticeTopicsIndexRouteImport } from './routes/practice.topics.index'
import { Route as PracticeTopicsTopicSlugRouteImport } from './routes/practice.topics.$topicSlug'
import { Route as ApiPublicHooksWeeklyDigestRouteImport } from './routes/api/public/hooks/weekly-digest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CpZoneRoute = CpZoneRouteImport.update({
  id: '/cp-zone',
  path: '/cp-zone',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionaryRoute = DictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceRoute = ReferenceRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMenteesRoute = AuthenticatedMenteesRouteImport.update({
  id: '/mentees',
  path: '/mentees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportingRoute = AuthenticatedReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CertificateCertificateCodeRoute =
  CertificateCertificateCodeRouteImport.update({
    id: '/certificate/$certificateCode',
    path: '/certificate/$certificateCode',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumPostIdRoute = ForumPostIdRouteImport.update({
  id: '/forum/$postId',
  path: '/forum/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCourseIdRoute = LearnCourseIdRouteImport.update({
  id: '/learn/$courseId',
  path: '/learn/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsIndexRoute = PathsIndexRouteImport.update({
  id: '/paths/',
  path: '/paths/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsPathIdRoute = PathsPathIdRouteImport.update({
  id: '/paths/$pathId',
  path: '/paths/$pathId',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin_/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedForumNewRoute = AuthenticatedForumNewRouteImport.update({
  id: '/forum/new',
  path: '/forum/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupsGroupIdRoute =
  AuthenticatedGroupsGroupIdRouteImport.update({
    id: '/groups/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileUserIdRoute =
  AuthenticatedProfileUserIdRouteImport.update({
    id: '/profile/$userId',
    path: '/profile/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PracticeTopicsIndexRoute = PracticeTopicsIndexRouteImport.update({
  id: '/practice/topics/',
  path: '/practice/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeTopicsTopicSlugRoute = PracticeTopicsTopicSlugRouteImport.update({
  id: '/practice/topics/$topicSlug',
  path: '/practice/topics/$topicSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksWeeklyDigestRoute =
  ApiPublicHooksWeeklyDigestRouteImport.update({
    id: '/api/public/hooks/weekly-digest',
    path: '/api/public/hooks/weekly-digest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cp-zone': typeof CpZoneRoute
  '/dictionary': typeof DictionaryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reference': typeof ReferenceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/mentees': typeof AuthenticatedMenteesRoute
  '/reporting': typeof AuthenticatedReportingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/certificate/$certificateCode': typeof CertificateCertificateCodeRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/forum/$postId': typeof ForumPostIdRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/paths/$pathId': typeof PathsPathIdRoute
  '/events/': typeof EventsIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/paths/': typeof PathsIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/forum/new': typeof AuthenticatedForumNewRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/practice/topics/$topicSlug': typeof PracticeTopicsTopicSlugRoute
  '/groups/': typeof AuthenticatedGroupsIndexRoute
  '/practice/topics/': typeof PracticeTopicsIndexRoute
  '/api/public/hooks/weekly-digest': typeof ApiPublicHooksWeeklyDigestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cp-zone': typeof CpZoneRoute
  '/dictionary': typeof DictionaryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reference': typeof ReferenceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/mentees': typeof AuthenticatedMenteesRoute
  '/reporting': typeof AuthenticatedReportingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/certificate/$certificateCode': typeof CertificateCertificateCodeRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/forum/$postId': typeof ForumPostIdRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/paths/$pathId': typeof PathsPathIdRoute
  '/events': typeof EventsIndexRoute
  '/forum': typeof ForumIndexRoute
  '/learn': typeof LearnIndexRoute
  '/paths': typeof PathsIndexRoute
  '/practice': typeof PracticeIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/forum/new': typeof AuthenticatedForumNewRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/practice/topics/$topicSlug': typeof PracticeTopicsTopicSlugRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/practice/topics': typeof PracticeTopicsIndexRoute
  '/api/public/hooks/weekly-digest': typeof ApiPublicHooksWeeklyDigestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cp-zone': typeof CpZoneRoute
  '/dictionary': typeof DictionaryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reference': typeof ReferenceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/mentees': typeof AuthenticatedMenteesRoute
  '/_authenticated/reporting': typeof AuthenticatedReportingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/certificate/$certificateCode': typeof CertificateCertificateCodeRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/forum/$postId': typeof ForumPostIdRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/paths/$pathId': typeof PathsPathIdRoute
  '/events/': typeof EventsIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/paths/': typeof PathsIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/_authenticated/admin_/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/forum/new': typeof AuthenticatedForumNewRoute
  '/_authenticated/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/_authenticated/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/practice/topics/$topicSlug': typeof PracticeTopicsTopicSlugRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/practice/topics/': typeof PracticeTopicsIndexRoute
  '/api/public/hooks/weekly-digest': typeof ApiPublicHooksWeeklyDigestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cp-zone'
    | '/dictionary'
    | '/leaderboard'
    | '/reference'
    | '/reset-password'
    | '/admin'
    | '/mentees'
    | '/reporting'
    | '/settings'
    | '/certificate/$certificateCode'
    | '/events/$eventId'
    | '/forum/$postId'
    | '/learn/$courseId'
    | '/paths/$pathId'
    | '/events/'
    | '/forum/'
    | '/learn/'
    | '/paths/'
    | '/practice/'
    | '/admin/analytics'
    | '/forum/new'
    | '/groups/$groupId'
    | '/profile/$userId'
    | '/practice/topics/$topicSlug'
    | '/groups/'
    | '/practice/topics/'
    | '/api/public/hooks/weekly-digest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cp-zone'
    | '/dictionary'
    | '/leaderboard'
    | '/reference'
    | '/reset-password'
    | '/admin'
    | '/mentees'
    | '/reporting'
    | '/settings'
    | '/certificate/$certificateCode'
    | '/events/$eventId'
    | '/forum/$postId'
    | '/learn/$courseId'
    | '/paths/$pathId'
    | '/events'
    | '/forum'
    | '/learn'
    | '/paths'
    | '/practice'
    | '/admin/analytics'
    | '/forum/new'
    | '/groups/$groupId'
    | '/profile/$userId'
    | '/practice/topics/$topicSlug'
    | '/groups'
    | '/practice/topics'
    | '/api/public/hooks/weekly-digest'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cp-zone'
    | '/dictionary'
    | '/leaderboard'
    | '/reference'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/mentees'
    | '/_authenticated/reporting'
    | '/_authenticated/settings'
    | '/certificate/$certificateCode'
    | '/events/$eventId'
    | '/forum/$postId'
    | '/learn/$courseId'
    | '/paths/$pathId'
    | '/events/'
    | '/forum/'
    | '/learn/'
    | '/paths/'
    | '/practice/'
    | '/_authenticated/admin_/analytics'
    | '/_authenticated/forum/new'
    | '/_authenticated/groups/$groupId'
    | '/_authenticated/profile/$userId'
    | '/practice/topics/$topicSlug'
    | '/_authenticated/groups/'
    | '/practice/topics/'
    | '/api/public/hooks/weekly-digest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CpZoneRoute: typeof CpZoneRoute
  DictionaryRoute: typeof DictionaryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ReferenceRoute: typeof ReferenceRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CertificateCertificateCodeRoute: typeof CertificateCertificateCodeRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  ForumPostIdRoute: typeof ForumPostIdRoute
  LearnCourseIdRoute: typeof LearnCourseIdRoute
  PathsPathIdRoute: typeof PathsPathIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ForumIndexRoute: typeof ForumIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  PathsIndexRoute: typeof PathsIndexRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
  PracticeTopicsTopicSlugRoute: typeof PracticeTopicsTopicSlugRoute
  PracticeTopicsIndexRoute: typeof PracticeTopicsIndexRoute
  ApiPublicHooksWeeklyDigestRoute: typeof ApiPublicHooksWeeklyDigestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cp-zone': {
      id: '/cp-zone'
      path: '/cp-zone'
      fullPath: '/cp-zone'
      preLoaderRoute: typeof CpZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary': {
      id: '/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof DictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentees': {
      id: '/_authenticated/mentees'
      path: '/mentees'
      fullPath: '/mentees'
      preLoaderRoute: typeof AuthenticatedMenteesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reporting': {
      id: '/_authenticated/reporting'
      path: '/reporting'
      fullPath: '/reporting'
      preLoaderRoute: typeof AuthenticatedReportingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/certificate/$certificateCode': {
      id: '/certificate/$certificateCode'
      path: '/certificate/$certificateCode'
      fullPath: '/certificate/$certificateCode'
      preLoaderRoute: typeof CertificateCertificateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$postId': {
      id: '/forum/$postId'
      path: '/forum/$postId'
      fullPath: '/forum/$postId'
      preLoaderRoute: typeof ForumPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$courseId': {
      id: '/learn/$courseId'
      path: '/learn/$courseId'
      fullPath: '/learn/$courseId'
      preLoaderRoute: typeof LearnCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths/': {
      id: '/paths/'
      path: '/paths'
      fullPath: '/paths/'
      preLoaderRoute: typeof PathsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths/$pathId': {
      id: '/paths/$pathId'
      path: '/paths/$pathId'
      fullPath: '/paths/$pathId'
      preLoaderRoute: typeof PathsPathIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin_/analytics': {
      id: '/_authenticated/admin_/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forum/new': {
      id: '/_authenticated/forum/new'
      path: '/forum/new'
      fullPath: '/forum/new'
      preLoaderRoute: typeof AuthenticatedForumNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/$groupId': {
      id: '/_authenticated/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/$userId': {
      id: '/_authenticated/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AuthenticatedProfileUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/practice/topics/': {
      id: '/practice/topics/'
      path: '/practice/topics'
      fullPath: '/practice/topics/'
      preLoaderRoute: typeof PracticeTopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/topics/$topicSlug': {
      id: '/practice/topics/$topicSlug'
      path: '/practice/topics/$topicSlug'
      fullPath: '/practice/topics/$topicSlug'
      preLoaderRoute: typeof PracticeTopicsTopicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-digest': {
      id: '/api/public/hooks/weekly-digest'
      path: '/api/public/hooks/weekly-digest'
      fullPath: '/api/public/hooks/weekly-digest'
      preLoaderRoute: typeof ApiPublicHooksWeeklyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMenteesRoute: typeof AuthenticatedMenteesRoute
  AuthenticatedReportingRoute: typeof AuthenticatedReportingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedForumNewRoute: typeof AuthenticatedForumNewRoute
  AuthenticatedGroupsGroupIdRoute: typeof AuthenticatedGroupsGroupIdRoute
  AuthenticatedProfileUserIdRoute: typeof AuthenticatedProfileUserIdRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMenteesRoute: AuthenticatedMenteesRoute,
  AuthenticatedReportingRoute: AuthenticatedReportingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedForumNewRoute: AuthenticatedForumNewRoute,
  AuthenticatedGroupsGroupIdRoute: AuthenticatedGroupsGroupIdRoute,
  AuthenticatedProfileUserIdRoute: AuthenticatedProfileUserIdRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CpZoneRoute: CpZoneRoute,
  DictionaryRoute: DictionaryRoute,
  LeaderboardRoute: LeaderboardRoute,
  ReferenceRoute: ReferenceRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CertificateCertificateCodeRoute: CertificateCertificateCodeRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  ForumPostIdRoute: ForumPostIdRoute,
  LearnCourseIdRoute: LearnCourseIdRoute,
  PathsPathIdRoute: PathsPathIdRoute,
  EventsIndexRoute: EventsIndexRoute,
  ForumIndexRoute: ForumIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  PathsIndexRoute: PathsIndexRoute,
  PracticeIndexRoute: PracticeIndexRoute,
  PracticeTopicsTopicSlugRoute: PracticeTopicsTopicSlugRoute,
  PracticeTopicsIndexRoute: PracticeTopicsIndexRoute,
  ApiPublicHooksWeeklyDigestRoute: ApiPublicHooksWeeklyDigestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
